open-mmlab/mmrazor

- requirements/mminstall.txt
The `revert_sync_batchnorm ` used in `DetNAS` is a new feature in `mmcv=1.3.13`, so we need update required mmcv version(#20)
`requirements/mminstall.txt`
update required mmcv version from `mmcv>=1.3.8,<=1.50` to `mmcv>1.3.13,<=1.50`
No
No
**Before PR**:
**After PR**:
> [Fix] update required mmcv version to `>=1.3.13`

- .gitignore
- setup.py
Use copy instead of symlink on windows to prevent `OSError: [WinError 1314]`.
Related issue: [open-mmlab/mmrazor#40](https://github.com/open-mmlab/mmrazor/issues/40).
`setup.py` & `.gitignore`.
**Before PR**:
> [Fix] Fix symlink error on windows

- README.md
- README_zh-CN.md
Since OpenMMLab's website and platform is open to the public, we hope that the users in GitHub could visit our new website and platform. This will help the people interested in OpenMMLab to experience our algorithms and models visually, and learn more about our codebases.
Add OpenMMLab's website and platform links and mmdeploy link in `README.md` and `README_zh-CN.md`.
**Before PR**:
> [Docs] Add OpenMMLab website and platform links and mmdeploy link

- mmrazor/apis/mmdet/train.py
- mmrazor/apis/mmseg/train.py
Hi! Related to [open-mmlab/mmdet#7016](https://github.com/open-mmlab/mmdetection/pull/7016), CPU training in MMRazor is supported in this pr. 
We modified the train api in ``mmrazor/apis/mmdet(mmseg)/train.py`` while kept ``mmrazor/apis/mmcls/train.py`` the same.
Now we can use the CPU to train/debug our model and test our model with batch size >=2. Before running the program we need to export CUDA_VISIBLE_DEVICES=-1 to disable GPU visibility.
> [Feature] Support CPU training

- tools/mmcls/test_mmcls.py
- tools/mmcls/train_mmcls.py
- tools/mmdet/test_mmdet.py
- tools/mmdet/train_mmdet.py
- tools/mmseg/test_mmseg.py
- tools/mmseg/train_mmseg.py
Refer pr: [open-mmlab/mmdetection#7019](https://github.com/open-mmlab/mmdetection/pull/7019).
`train(test)_xxx.py` under tools directory.
**Before PR**:
> [Fix] Fix bug in non-distributed training/testing for all tasks

- requirements/optional.txt
- setup.py
Refers to https://github.com/open-mmlab/mmcv/pull/1637
Update the setup.py
**Before PR**:
**After PR**:
> [Refactor]Deprecate the support for ``python setup.py test``

- .pre-commit-config.yaml
- setup.cfg
1. Remove ``seed-isort-config`` in pre-commit hook
2. Upgrade ``isort`` to v5.10.1 (latest version)
3. Replace ``known_standard_library`` with ``extra_standard_library``
> [Enhancement]Upgrade isort in pre-commit hook

- .pre-commit-config.yaml
- configs/distill/cwd/README.md
- configs/distill/wsld/README.md
- configs/nas/darts/README.md
- configs/nas/detnas/README.md
- configs/nas/spos/README.md
- configs/pruning/autoslim/README.md
- requirements/optional.txt
- setup.cfg
- setup.py
As the title.
**Before PR**:
**After PR**:
> [Docs]Update README according to OpenMMLab standard.

- .github/workflows/build.yml
- .github/workflows/lint.yml
Refer pr: [open-mmlab/mmediting#732](https://github.com/open-mmlab/mmediting/pull/732).
> [CI] Add CI for windows and redesign CI

- .pre-commit-config.yaml
replace `markdownlint`'s mapping github refering to `mmdet`, it is more friendly for users to develop in local.
**Before PR**:
**After PR**:
> [CI] update pre-commit-config

- tools/mmcls/dist_search.sh
- tools/mmcls/dist_test.sh
- tools/mmcls/dist_train.sh
- tools/mmdet/dist_search.sh
- tools/mmdet/dist_test.sh
- tools/mmdet/dist_train.sh
- tools/mmseg/dist_test.sh
- tools/mmseg/dist_train.sh
Add scripts for simplify distributed training/searching/testing.
tools/xxx/dist_xxx.sh.
**Before PR**:
> [Enhancement] Add distributed scripts

- README.md
- README_zh-CN.md
Ref to mmediting [#800](https://github.com/open-mmlab/mmediting/pull/800) and [#816](https://github.com/open-mmlab/mmediting/pull/816).
> [Docs] Add brief installation steps in README(_zh-CN).md

- mmrazor/apis/mmcls/train.py
- mmrazor/apis/mmdet/train.py
API train.py in sync with mmcls([#588](https://github.com/open-mmlab/mmclassification/pull/588) and [#611](https://github.com/open-mmlab/mmclassification/pull/611)) and mmdet([#6435](https://github.com/open-mmlab/mmdetection/pull/6435)).
> [Fix]Sync train api

- mmrazor/apis/mmcls/train.py
- mmrazor/apis/mmseg/train.py
- tools/mmcls/test_mmcls.py
- tools/mmseg/test_mmseg.py
In some situation, we need to use different dataloader settings like samples_per_gpu in train/val/test dataloader.
**refer pr**:
[open-mmlab/mmclassification#752](https://github.com/open-mmlab/mmclassification/pull/752)
[open-mmlab/mmsegmentation#1435](https://github.com/open-mmlab/mmsegmentation/pull/1435)
[open-mmlab/mmdetection#7668](https://github.com/open-mmlab/mmdetection/pull/7668)
Use train_dataloader, val_dataloader and test_dataloader settings in the data field to specify different arguments.
```python
data = dict(
samples_per_gpu=64,
workers_per_gpu=4,
train=dict(type='xxx', ...),
val=dict(type='xxx', ...),
test=dict(type='xxx', ...),
val_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2),
test_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2),
)
```
> [Enhance] Add extra dataloader settings in configs

- mmrazor/core/searcher/evolution_search.py
- mmrazor/core/searcher/greedy_search.py
- mmrazor/core/utils/__init__.py
- mmrazor/core/utils/broadcast.py
- mmrazor/core/utils/utils.py
fix init bug when running in single GPU #42
fix broadcast_object_list bug, which can not be executed in multi-machines.
Refactor `broadcast_object_list` to be consistent with pytorch
1. new `broad_object_list` is without return value.
2. `broad_object_list`'s parameter changed: `object_list` -> `data`
Examples:
>>> import torch
>>> import mmrazor.core.utils as dist
>>> # non-distributed environment
>>> data = ['foo', 12, {1: 2}]
>>> dist.broadcast_object_list(data)
>>> data
['foo', 12, {1: 2}]
>>> # distributed environment
>>> # We have 2 process groups, 2 ranks.
>>> if dist.get_rank() == 0:
>>>     # Assumes world_size of 3.
>>>     data = ["foo", 12, {1: 2}]  # any picklable object
>>> else:
>>>     data = [None, None, None]
>>> dist.broadcast_object_list(data)
>>> data
["foo", 12, {1: …
> [Enhancement]Support broadcast_object_list in multi-machines & support Searcher running in single GPU

- mmrazor/models/pruners/ratio_pruning.py
- mmrazor/models/pruners/structure_pruning.py
- tests/test_models/test_algorithms/test_algorithm.py
- tests/test_models/test_pruner.py
> [BUG]Support to prune models containing GroupNorm or InstanceNorm.

- mmrazor/models/pruners/structure_pruning.py
autoslim get subnet by split_checkpoints is wrone.
```python
module.weight = nn.Parameter(temp_weight.data.clone())
module.bias = nn.Parameter(module.bias.data[:out_channels].clone())
```
If this PR introduces a new feature, it is better to list some use cases here and update …
> [Bug]fix: split autoslim different checkpoint has equal model size

- mmrazor/models/pruners/structure_pruning.py
fix bug in find_make_group_parser for depthwise
https://github.com/open-mmlab/mmrazor/issues/177
mmrazor/models/pruners/structure_pruning.py
> fix bug in find_make_group_parser for depthwise

- mmrazor/engine/runner/darts_loop.py
Fix darts loop
before
after
**Before PR**:
**After PR**:
> [Fix] Fix EpochMultiDataloader in darts loop

- mmrazor/engine/runner/darts_loop.py
- tests/test_runners/test_darts_loop.py
fixed darts loop unittest, passed pre-commit and pytest in local 
**Before PR**:
**After PR**:
> [Bug] Fix darts loop unittest

- mmrazor/models/mutables/mutable_module/diff_mutable_module.py
- mmrazor/models/mutators/module_mutator/diff_module_mutator.py
- tests/test_models/test_algorithms/test_autoslim.py
- tests/test_models/test_algorithms/test_slimmable_network.py
- tests/test_models/test_mutables/test_diffchoiceroute.py
- tests/test_models/test_mutables/test_diffop.py
- tests/test_models/test_mutables/test_gumbelchoiceroute.py
- tests/test_models/test_mutators/test_classical_models/test_mbv2_channel_mutator.py
- tests/test_models/test_mutators/test_diff_mutator.py
- tests/test_runners/test_darts_loop.py
> [Refactor] Move `build_arch_param` from `DiffMutableModule` to `DiffModuleMutator`

- mmrazor/models/mutables/__init__.py
- mmrazor/models/mutables/derived_mutable.py
- mmrazor/models/mutables/mutable_channel/mutable_channel.py
- mmrazor/models/mutables/mutable_channel/one_shot_mutable_channel.py
- mmrazor/models/mutables/mutable_channel/slimmable_mutable_channel.py
- mmrazor/models/mutables/mutable_value/__init__.py
- mmrazor/models/mutables/mutable_value/mutable_value.py
- mmrazor/models/utils/__init__.py
- mmrazor/models/utils/make_divisible.py
- mmrazor/structures/subnet/fix_subnet.py
- tests/test_models/test_mutables/test_derived_mutable.py
- tests/test_models/test_mutables/test_mutable_value.py
- tests/test_models/test_subnet/test_fix_subnet.py
Add `DerivedMutable` and `MutableValue`.
1. Add `DerivedMutable`
2. Add `MutableValue`
3. Fix mmcls import error
> [Feature] Add `DerivedMutable` & `MutableValue`

- mmrazor/models/mutables/derived_mutable.py
- requirements/runtime.txt
Fix `Protocol` import error when python<3.8.
1. Import `Protocol` from typing_extensions when python<3.8
2. Add `typing_extensions` in requirements/runtime.txt when python<3.8
> [Fix] Fix `Protocol` import error when python<3.8

- mmrazor/engine/runner/evolution_search_loop.py
- mmrazor/engine/runner/subnet_sampler_loop.py
- mmrazor/models/algorithms/pruning/slimmable_network.py
- mmrazor/models/architectures/dynamic_op/__init__.py
- mmrazor/models/architectures/dynamic_op/base.py
- mmrazor/models/architectures/dynamic_op/bricks/__init__.py
- mmrazor/models/architectures/dynamic_op/bricks/dynamic_conv.py
- mmrazor/models/architectures/dynamic_op/bricks/dynamic_conv_mixins.py
- mmrazor/models/architectures/dynamic_op/bricks/dynamic_linear.py
- mmrazor/models/architectures/dynamic_op/bricks/dynamic_mixins.py
- mmrazor/models/architectures/dynamic_op/bricks/dynamic_norm.py
- mmrazor/models/architectures/dynamic_op/default_dynamic_ops.py
- mmrazor/models/architectures/dynamic_op/head/__init__.py
- mmrazor/models/mutables/__init__.py
- mmrazor/models/mutables/derived_mutable.py
- mmrazor/models/mutables/mutable_channel/mutable_channel.py
- mmrazor/models/mutables/mutable_channel/slimmable_mutable_channel.py
- mmrazor/models/mutables/mutable_manage_mixin.py
- mmrazor/structures/subnet/fix_subnet.py
- tests/test_models/test_algorithms/test_slimmable_network.py
- tests/test_models/test_architectures/test_dynamic_op/__init__.py
- tests/test_models/test_architectures/test_dynamic_op/test_bricks/__init__.py
- tests/test_models/test_architectures/test_dynamic_op/test_bricks/test_dynamic_conv.py
- tests/test_models/test_architectures/test_dynamic_op/test_bricks/test_dynamic_linear.py
- tests/test_models/test_architectures/test_dynamic_op/test_bricks/test_dynamic_norm.py
- tests/test_models/test_architectures/test_dynamic_op/test_default_dynamic_op.py
- tests/test_models/test_architectures/test_dynamic_op/utils.py
- tests/test_models/test_mutators/utils.py
- tests/test_runners/test_evolution_search_loop.py
Add dynamic bricks
1. Add dynamic Conv2d and corresponding unittest/docstring.
2. Add dynamic Linear and corresponding unittest/docstring.
3. Add dynamic BatchNormxd and corresponding unittest/docstring.
4. Delete MutableManageMixin
No.
> [Feature] Add dynamic bricks

- mmrazor/models/architectures/backbones/searchable_mobilenet.py
- mmrazor/models/architectures/backbones/searchable_shufflenet_v2.py
- mmrazor/models/architectures/heads/darts_subnet_head.py
- mmrazor/models/losses/kd_soft_ce_loss.py
- mmrazor/models/ops/efficientnet_series.py
- mmrazor/models/ops/mobilenet_series.py
- mmrazor/models/ops/shufflenet_series.py
- mmrazor/structures/tracer/loss_calculator/image_classifier_loss_calculator.py
- mmrazor/utils/__init__.py
- mmrazor/utils/placeholder.py
- requirements/mminstall.txt
- requirements/optional.txt
- requirements/readthedocs.txt
- requirements/runtime.txt
- requirements/tests.txt
Decouple dependencies.
add get_placeholder function
**Before PR**:
**After PR**:
> [Improvement] Decouple dependency

- configs/nas/mmcls/spos/spos_mobilenet_search_8xb128_in1k.py
- configs/nas/mmcls/spos/spos_shufflenet_search_8xb128_in1k.py
- configs/nas/mmdet/detnas/detnas_frcnn_shufflenet_search_coco_1x.py
- mmrazor/engine/runner/evolution_search_loop.py
- mmrazor/engine/runner/subnet_sampler_loop.py
- mmrazor/engine/runner/utils/__init__.py
- mmrazor/engine/runner/utils/check.py
- mmrazor/models/task_modules/estimators/base_estimator.py
- mmrazor/models/task_modules/estimators/counters/__init__.py
- mmrazor/models/task_modules/estimators/counters/flops_params_counter.py
- mmrazor/models/task_modules/estimators/counters/latency_counter.py
- mmrazor/models/task_modules/estimators/resource_estimator.py
- mmrazor/models/task_modules/tracer/loss_calculator/single_stage_detector_loss_calculator.py
- tests/test_models/test_task_modules/test_estimators/test_flops_params.py
- tests/test_runners/test_evolution_search_loop.py
- tests/test_runners/test_subnet_sampler_loop.py
- tests/test_runners/test_utils/test_check.py
- Update ResourceEstimator with more init_cfgs.
- Add units prefix in measurement.
- Update UTs in estimator & runner_loops.
If this PR introduces a new feature, it is better to list …
> [Improvement] Update estimator with api revision

- mmrazor/models/utils/make_divisible.py
Fix a bug in make_divisible.
Fix a bug in make_divisible. (It influents autoslim training.)
>  Fix a bug in make_divisible.

- mmrazor/models/task_modules/estimators/counters/flops_params_counter.py
- tests/test_models/test_task_modules/test_estimators/test_flops_params.py
> [Fix] Fix counter mapping bug

- README.md
- README_zh-CN.md
- docs/en/user_guides/2_train_different_types_algorithms.md
> add MMYOLO projects link

- mmrazor/models/task_modules/delivery/distill_delivery.py
- mmrazor/models/task_modules/delivery/function_outputs_delivery.py
- mmrazor/models/task_modules/delivery/method_outputs_delivery.py
- mmrazor/models/task_modules/recorder/__init__.py
- mmrazor/models/task_modules/recorder/function_inputs_recorder.py
- mmrazor/models/task_modules/recorder/function_outputs_recorder.py
- mmrazor/models/task_modules/recorder/method_inputs_recorder.py
- mmrazor/models/task_modules/recorder/method_outputs_recorder.py
- tests/test_core/test_delivers/test_function_outputs_deliver.py
- tests/test_core/test_recorders/test_func_inputs_recorder.py
- tests/test_core/test_recorders/test_func_outputs_recorder.py
- tests/test_core/test_recorders/test_method_inputs_recorder.py
- tests/test_core/test_recorders/toy_mod.py
1.  Add `MethodInputsRecorder` and `FunctionInputsRecorder`
2. Fix the bug when ema_hook is used. (deepcopy is used in ema_hook and module objects can not be pickled)
> [Features]Support `MethodInputsRecorder` and `FunctionInputsRecorder`

- mmrazor/apis/mmseg/train.py
Motivation
The mmseg api now only supports iter based runner since there is no DistSamplerSeedHook registered.
This PR adds the DistSamplerSeedHook in mmrazor\apis\mmseg\train.py to facilitate epoch based runner for mmseg
Modification
Add DistSamplerSeedHook and register it if the runner is epoch based runner. (line 138 in mmrazor\apis\mmseg\train.py)
this pr is a copy of https://github.com/open-mmlab/mmrazor/pull/325
> add DistSamplerSeedHook to support epoch based runner in mmrazor for mmseg

- configs/quantization/ptq/adaround.py
- configs/quantization/qat/demo.py
- configs/quantization/qat/lsq_resnet18_8xb16_cifar10.py
- configs/quantization/qat/lsq_resnet18_8xb32_in1k.py
- mmrazor/engine/__init__.py
- mmrazor/engine/runner/__init__.py
- mmrazor/engine/runner/quantization_loops.py
- mmrazor/models/algorithms/__init__.py
- mmrazor/models/algorithms/quantization/base.py
- mmrazor/models/fake_quants/lsq.py
- mmrazor/models/losses/__init__.py
- mmrazor/models/mutables/mutable_channel/units/mutable_channel_unit.py
- mmrazor/models/observers/__init__.py
- mmrazor/models/observers/base.py
- mmrazor/models/observers/minmax.py
- mmrazor/models/quantizers/base.py
- mmrazor/models/quantizers/trt_quantizer.py
- mmrazor/models/task_modules/__init__.py
- mmrazor/models/task_modules/tracer/__init__.py
- mmrazor/models/task_modules/tracer/fx/__init__.py
- mmrazor/models/task_modules/tracer/fx/custom_tracer.py
- mmrazor/registry/registry.py
- mmrazor/structures/quantization/__init__.py
- mmrazor/structures/quantization/backend_default_qconfigs.py
- tools/ptq_calibrate.py
> [Features]Quantize pipeline

- configs/distill/mmcls/ofd/ofd_backbone_resnet50_resnet18_8xb16_cifar10.py
- configs/vanilla/mmcls/wide-resnet/README.md
- configs/vanilla/mmcls/wide-resnet/wrn22-w4_b16x8_cifar10.py
- configs/vanilla/mmcls/wide-resnet/wrn28-w4_b16x8_cifar10.py
- configs/vanilla/mmcls/wide-resnet/wrn40-w2_b16x8_cifar10.py
1.Revise the configs of wrn22, wrn24, and wrn40. 
2.Revise the data_preprocessor of ofd_backbone_resnet50_resnet18_8xb16_cifar10
> [Fix] Fix configs of wrn models and ofd.

- tools/visualizations/feature_diff_visualization.py
- tools/visualizations/feature_visualization.py
Hi, when i use the [MMRazor visualization](https://github.com/open-mmlab/mmrazor/blob/dev-1.x/docs/zh_cn/user_guides/visualization.md), i found the mismatch argument in define and use. Specifically, the define arg is `vis-config` but in use is `args.vis_config`, causing `AttributeError: 'Namespace' object has no attribute 'vis_config'` in my environment.
change `vis-config` to `vis_config`
If so, please describe how it …
> [Fix] Fix bug on mmrazor visualization, mismatch argument in define and use.

- mmrazor/models/algorithms/distill/configurable/fpn_teacher_distill.py
> [Bug]Fix fpn teacher distill

- mmrazor/models/quantizers/base.py
- mmrazor/models/quantizers/native_quantizer.py
- mmrazor/models/quantizers/openvino_quantizer.py
- mmrazor/models/task_modules/tracer/fx/__init__.py
- mmrazor/models/task_modules/tracer/fx/graph_utils.py
- tests/test_models/test_task_modules/test_graph_utils.py
1. Refactor graph_utils: We support deleting fakequant before / after  op / method / function / module in graph_utils.
2. Add 8 properties to `BaseQuantizer`. Each is a tuple. For example, the `module_del_prev_fakequant` property in `OpenVINOQuantizer` is (torch.nn.ReLU6, torch.nn.Identity). These properties are determined by the backend, so maybe they need to be regarded as properties.
3. Add the corresponding pytest and docstring.
> [Refactor & Doc] Refactor graph_utils and add docstring and pytest

- mmrazor/models/quantizers/academic_quantizer.py
- mmrazor/models/quantizers/native_quantizer.py
- mmrazor/models/task_modules/tracer/fx/custom_tracer.py
- mmrazor/structures/quantization/qconfig.py
- tests/data/test_models/test_task_modules/mmcls_cfg.py
- tests/test_models/test_task_modules/test_custom_tracer.py
- tests/test_models/test_task_modules/test_graph_utils.py
- tests/test_structures/test_qconfig.py
1. rename QConfigHander -> QConfigHandler ;  QSchemeHander -> QSchemeHandler
2. add docstring and unittest: `UntracedMethodRegistry`, `CustomTracer`, `build_graphmodule`,  `custom_symbolic_trace`
> [Docs] Add docstring and unitest about custom tracer

- mmrazor/engine/runner/distill_val_loop.py
`SingleTeacherDistillValLoop` calls `after_val_epoch` hooks twice during the evaluation. However, the metric in the second call do not contain the key named `student.accuracy/top1`. As a result, if we set `save_best='auto'` in `CheckpointHook`, the program will fail.
Please refer to this [issue](https://github.com/open-mmlab/mmrazor/issues/396#issuecomment-1369535233) for more details.
Now we only call `after_val_epoch` hooks once in `SingleTeacherDistillValLoop`.
> call after_val_epoch hooks only once to save best ckpt correctly

- mmrazor/models/distillers/ofd_distiller.py
Fix OfdDistiller when the names of bn modules are different between teacher and student
It would fetch the name of student modules from teacher, this is not reasonable and cause exceptions if the names are not identical between student and teacher.
Also, we only need to do this if `from_student=False`, so i moved the code under the if condition.
I moved the code under the if condition to fix the moudleName-notfound bug. …
> [BugFix] Fix OfdDistiller when the names of bn modules are different between teacher and student

- mmrazor/models/architectures/connectors/mgd_connector.py
- tests/test_models/test_architectures/test_connectors/test_connectors.py
From the paper, they also masked out the channel when training classification model, and got the better result.
Support to mask out channel
**Before PR**:
**After PR**:
> [Feature] Add mask channel in MGD Loss

- configs/pruning/mmcls/dmcp/metafile.yml
- configs/pruning/mmcls/group_fisher/mobilenet/metafile.yml
- configs/pruning/mmcls/group_fisher/resnet50/metafile.yml
- configs/pruning/mmcls/l1-norm/README.md
- configs/pruning/mmcls/l1-norm/l1-norm_resnet34_8xb32_in1k_a_deploy.py
- configs/pruning/mmcls/l1-norm/l1-norm_resnet34_8xb32_in1k_b_deploy.py
- configs/pruning/mmcls/l1-norm/l1-norm_resnet34_8xb32_in1k_c_deploy.py
- configs/pruning/mmcls/l1-norm/metafile.yml
- configs/pruning/mmcls/l1-norm/script.sh
- configs/pruning/mmdet/group_fisher/retinanet/metafile.yml
- model-index.yml
- tools/pruning/get_static_model_from_algorithm.py
Add a tool named get_static_model_from_algorithm and deploy guide for l1-norm
> Add a tool named get_static_model_from_algorithm and deploy guide for l1-norm

- mmrazor/models/mutables/mutable_channel/units/mutable_channel_unit.py
- mmrazor/models/mutators/channel_mutator/channel_mutator.py
- mmrazor/models/task_modules/tracer/channel_analyzer.py
- mmrazor/models/utils/expandable_utils/ops.py
fix bug when deploy a pruned model to cuda.
> fix bug when deploy a pruned model to cuda.

- mmrazor/engine/runner/quantization_loops.py
- mmrazor/models/fake_quants/torch_fake_quants.py
- mmrazor/models/observers/torch_observers.py
> [Bug] Try to fix CI

- .github/workflows/build.yml
- .pre-commit-config.yaml
- mmrazor/engine/runner/quantization_loops.py
- mmrazor/models/algorithms/quantization/mm_architecture.py
- mmrazor/models/fake_quants/lsq.py
- mmrazor/models/fake_quants/torch_fake_quants.py
- mmrazor/models/observers/torch_observers.py
- tests/test_models/test_algorithms/test_mm_architecture.py
- tests/test_models/test_fake_quants/test_lsq_fake_quants.py
> [Feature] Support lsq new

- mmrazor/models/quantizers/exporters/base_quantize_exporter.py
- mmrazor/models/quantizers/exporters/openvino_quantize_exporter.py
- mmrazor/models/quantizers/exporters/optim_utils.py
- mmrazor/models/quantizers/exporters/tensorrt_quantize_exporter.py
- requirements/tests.txt
- tests/test_models/test_quantizers/test_exporter.py
> [Feature] Add exporter pytest

- mmrazor/implementations/pruning/sparse_gpt/mutator.py
- mmrazor/implementations/pruning/sparse_gpt/ops.py
- projects/mmrazor_large/examples/model_examples/ResNet/sparse_gpt/resnet18_sparse_gpt.py
- projects/mmrazor_large/examples/model_examples/language_models/Llama/datautils.py
- projects/mmrazor_large/examples/model_examples/language_models/Llama/llama_sparse_gpt_fsdp.py
- projects/mmrazor_large/examples/model_examples/language_models/Llama/utils.py
- projects/mmrazor_large/examples/model_examples/language_models/OPT/opt_sparse_gpt_fsdp.py
- projects/mmrazor_large/examples/model_examples/language_models/OPT/utils.py
> refine sparse gpt
