open-mmlab/mmrazor

- requirements/readthedocs.txt
Update requirements for readthedocs.
- Add `mmcls` and `ordered_set` in `requirements/readthedocs.txt`.
> [Docs] Update requirements for readthedocs

- configs/pruning/autoslim/README.md
> [Docs]Update AutoSlim README.md

- configs/distill/wsld/wsld_cls_head_resnet34_resnet18_8xb32_in1k.py
Resolve: https://github.com/open-mmlab/mmrazor/issues/25
> Fix config error of wsld

- mmrazor/models/pruners/structure_pruning.py
Hi, a reference to https://github.com/jshilong/FisherPruning is added in this minor pr. Pls take a look.
> [Docs]Add a reference to StructurePruner

- configs/distill/wsld/wsld_cls_head_resnet34_resnet18_8xb32_in1k.py
- mmrazor/models/algorithms/base.py
- mmrazor/models/algorithms/general_distill.py
- mmrazor/models/distillers/base.py
- mmrazor/models/distillers/single_teacher.py
- mmrazor/models/losses/cwd.py
- mmrazor/models/losses/kl_divergence.py
- mmrazor/models/losses/weighted_soft_label_distillation.py
> [Docs] Fix some type of Distill

- tools/mmcls/search_mmcls.py
- tools/mmcls/test_mmcls.py
- tools/mmdet/search_mmdet.py
- tools/mmdet/test_mmdet.py
- tools/mmseg/test_mmseg.py
Fix `show_result` error during test.
Related issue: [open-mmlab/mmrazor#52](https://github.com/open-mmlab/mmrazor/issues/52).
Add attribute `CLASSES` and `PALETTE` to `algorithm.architecture.model` instead of `algorithm`.
**Before PR**:
**After PR**:
> [Fix] Fix `show_result` error during test

- docs/en/api.rst
- docs/zh_cn/api.rst
- mmrazor/utils/__init__.py
- mmrazor/utils/setup_env.py
- setup.cfg
- tests/test_utils/test_setup_env.py
- tools/mmcls/search_mmcls.py
- tools/mmcls/test_mmcls.py
- tools/mmcls/train_mmcls.py
- tools/mmdet/search_mmdet.py
- tools/mmdet/test_mmdet.py
- tools/mmdet/train_mmdet.py
- tools/mmseg/test_mmseg.py
- tools/mmseg/train_mmseg.py
Refer pr: [open-mmlab/mmdetection#7036](https://github.com/open-mmlab/mmdetection/pull/7036)
Modify xxx_train.py, xxx_test.py and xxx_search.py in tools, add setup_env.py and modify api.rst.
[Refer config](https://github.com/open-mmlab/mmdetection/blob/449a86c567f3b81c78d867f488f1c78f60304954/tests/test_utils/test_setup_env.py).
**Before PR**:
> [Enhance] Add setup multi-processes for all tasks

- .pre-commit-config.yaml
- configs/distill/cwd/README.md
- configs/distill/wsld/README.md
- configs/nas/darts/README.md
- configs/nas/detnas/README.md
- configs/nas/spos/README.md
- configs/pruning/autoslim/README.md
- mmrazor/apis/mmdet/train.py
- mmrazor/core/builder.py
- mmrazor/core/hooks/__init__.py
- mmrazor/core/optimizer/__init__.py
- mmrazor/core/optimizer/builder.py
- mmrazor/core/runners/__init__.py
- mmrazor/core/searcher/__init__.py
- mmrazor/core/utils/lr.py
- mmrazor/datasets/__init__.py
- mmrazor/datasets/utils.py
- mmrazor/models/architectures/components/backbones/darts_backbone.py
- mmrazor/models/architectures/components/heads/no_bias_fc_head.py
- mmrazor/models/ops/darts_series.py
- mmrazor/utils/__init__.py
- tests/data/cwd_pspnet.py
- tests/data/detnas_frcnn_shufflenet_fpn.py
- tests/data/retinanet.py
Refer pr: https://github.com/open-mmlab/mmdeploy/pull/166
> Add a new pre-commit-hook to automatically add a copyright

- README.md
- README_zh-CN.md
As the title.
Refer PR: https://github.com/open-mmlab/mmcv/pull/1744
**Before PR**:
**After PR**:
> [Enhancement] Reorganizing OpenMMLab projects in readme

- configs/nas/detnas/detnas_evolution_search_frcnn_shufflenetv2_fpn_coco.py
- configs/nas/detnas/detnas_supernet_frcnn_shufflenetv2_fpn_1x_coco.py
- configs/nas/spos/spos_evolution_search_shufflenetv2_8xb2048_in1k.py
> [Fix]Modify BN to SyncBN

- mmrazor/version.py
Bump version to v0.2.0
**Before PR**:
**After PR**:
> Bump version to v0.2.0

- mmrazor/apis/mmcls/__init__.py
- mmrazor/apis/mmcls/inference.py
- mmrazor/apis/mmdet/__init__.py
- mmrazor/apis/mmdet/inference.py
- mmrazor/apis/mmseg/__init__.py
- mmrazor/apis/mmseg/inference.py
- tests/test_apis/test_inference.py
- tests/test_inference.py
Add `init_xxx_model` to meet the need for mmdeploy.
Add `init_xxx_model` functions. 
**Before PR**:
> [Feature] Add function to meet mmdeploy support

- mmrazor/models/pruners/structure_pruning.py
- tests/test_models/test_pruner.py
Fix bugs in ``StructurePruner``.
1. Fix the bug of grouping errors caused by shared modules
2. Support trace Dilated Conv2d
3. Fix the bug that the modules whose ``requires_grad`` is False can not be traced
4. Modify the forward method in a correct way.
> [BUG]Fix bugs in pruner

- README.md
- README_zh-CN.md
- docs/en/dataset_prepare.md
- docs/en/test.md
- docs/en/train.md
> [Docs]Add some more details to docs

- .github/workflows/build.yml
- MANIFEST.in
- setup.py
Add MANIFEST.in to include requirement.
Add MANIFEST.in.
> [Installation] Add MANIFEST.in

- setup.py
Add mim to extras_require in setup.py
Update setup.py. Refer to https://github.com/open-mmlab/mmsegmentation/pull/1655
**Before PR**:
**After PR**:
> Add mim to extras_require in setup.py

- mmrazor/apis/mmdet/inference.py
- tests/test_apis/test_inference.py
Fix issue [open-mmlab/mmrazor#175](https://github.com/open-mmlab/mmrazor/issues/175).
Fix `init_mmdet_model`.
**Before PR**:
> [Fix] Fix init mmdet model api

- mmrazor/__init__.py
- mmrazor/models/architectures/heads/darts_subnet_head.py
- mmrazor/structures/subnet/fix_subnet.py
- tests/test_models/test_algorithms/test_autoslim.py
- tests/test_models/test_algorithms/test_slimmable_network.py
- tests/test_models/test_mutators/test_classical_models/test_mbv2_channel_mutator.py
- tools/test.py
Fix mmcv version and mmcls import error.
Fix mmcv dependence version and mmcls import error.
> [Fix] Fix mmcls import error

- tests/test_models/test_architectures/test_connectors/test_connectors.py
1. Fix the bug of connector AssertionError
**Before PR**:
**After PR**:
> [Fix] Fix AssertionError in test_connector

- mmrazor/models/mutables/derived_mutable.py
> [Bug]Fix iterable import bug

- configs/pruning/mmcls/autoslim/autoslim_mbv2_1.5x_supernet_8xb256_in1k.py
fix the bug in the config file of Autoslim
> [fix]fix config error of autoslim

- docs/en/get_started/installation.md
- docs/en/user_guides/2_train_different_types_algorithms.md
- docs/en/user_guides/3_train_with_different_devices.md
- docs/en/user_guides/4_test_a_model.md
- docs/en/user_guides/kd.md
- docs/en/user_guides/nas.md
- docs/en/user_guides/pruning.md
> [Doc] Add Tutorial of KD,Pruning,NAS and Installation.

- .circleci/config.yml
- .circleci/docker/Dockerfile
- .circleci/test.yml
- tools/model_converters/publish_model.py
> [CI] Add circle ci

- .circleci/test.yml
- .dev_scripts/benchmark_test.py
- configs/distill/mmcls/abloss/README.md
- configs/distill/mmcls/byot/README.md
- configs/distill/mmcls/dafl/README.md
- configs/distill/mmcls/fitnet/README.md
- configs/distill/mmdet/cwd/README.md
- configs/distill/mmdet/fbkd/README.md
- configs/nas/mmcls/spos/README.md
- configs/pruning/mmcls/autoslim/README.md
- docs/en/advanced_guides/algorithm.md
- docs/en/advanced_guides/apply_existing_algorithms_to_new_tasks.md
- docs/en/advanced_guides/customize_architectures.md
- docs/en/advanced_guides/customize_mixed_algorithms.md
- docs/en/advanced_guides/delivery.md
- docs/en/advanced_guides/mutable.md
- docs/en/advanced_guides/mutator.md
- docs/en/advanced_guides/recorder.md
- docs/en/get_started/overview.md
- docs/en/user_guides/1_learn_about_config.md
> [Enhancement] Add benchmark test script

- .circleci/test.yml
- .dev_scripts/benchmark_test.py
- configs/distill/mmcls/abloss/README.md
- configs/distill/mmcls/byot/README.md
- configs/distill/mmcls/dafl/README.md
- configs/distill/mmcls/fitnet/README.md
- configs/distill/mmdet/cwd/README.md
- configs/distill/mmdet/fbkd/README.md
- configs/nas/mmcls/spos/README.md
- configs/pruning/mmcls/autoslim/README.md
- docs/en/advanced_guides/algorithm.md
- docs/en/advanced_guides/apply_existing_algorithms_to_new_tasks.md
- docs/en/advanced_guides/customize_architectures.md
- docs/en/advanced_guides/customize_mixed_algorithms.md
- docs/en/advanced_guides/delivery.md
- docs/en/advanced_guides/mutable.md
- docs/en/advanced_guides/mutator.md
- docs/en/advanced_guides/recorder.md
- docs/en/get_started/overview.md
- docs/en/user_guides/1_learn_about_config.md
Reverts open-mmlab/mmrazor#262
> Revert "[Enhancement] Add benchmark test script"

- configs/nas/mmcls/spos/spos_mobilenet_search_8xb128_in1k.py
- configs/nas/mmdet/detnas/detnas_frcnn_shufflenet_search_coco_1x.py
- configs/nas/mmdet/detnas/detnas_frcnn_shufflenet_supernet_coco_1x.py
- mmrazor/engine/runner/evolution_search_loop.py
- mmrazor/engine/runner/subnet_sampler_loop.py
- mmrazor/models/task_modules/estimators/counters/flops_params_counter.py
- tests/test_runners/test_evolution_search_loop.py
- tests/test_runners/test_subnet_sampler_loop.py
- tools/slurm_train.sh
1. add search configs
2. fix check_constrains
3. fix ut
> Update search configs

- docs/en/notes/changelog_v1.md
> Bump version to 1.0.0rc0

- mmrazor/models/task_modules/estimators/counters/flops_params_counter.py
- mmrazor/models/task_modules/estimators/counters/latency_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/activation_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/conv_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/deconv_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/linear_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/norm_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/pooling_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/upsample_layer_counter.py
> [Docs] Complete Estimator doc strings

- .circleci/test.yml
- mmrazor/__init__.py
- requirements/mminstall.txt
> Update MMCV minimum version

- mmrazor/models/task_modules/estimators/counters/flops_params_counter.py
- mmrazor/models/task_modules/estimators/counters/latency_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/activation_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/conv_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/deconv_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/linear_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/norm_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/pooling_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/upsample_layer_counter.py
Reverts open-mmlab/mmrazor#260
> Revert "[Docs] Complete Estimator doc strings"

- mmrazor/models/task_modules/estimators/counters/flops_params_counter.py
- mmrazor/models/task_modules/estimators/counters/latency_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/activation_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/conv_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/deconv_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/linear_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/norm_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/pooling_layer_counter.py
- mmrazor/models/task_modules/estimators/counters/op_counters/upsample_layer_counter.py
> [Doc] Complete doc strings of estimators

- docs/en/user_guides/2_train_different_types_algorithms.md
Fix typos in en/usr_guides.
**Before PR**:
**After PR**:
> [Doc] fix typos in en/usr_guides

- tools/train.py
Following pr#8461, pr#8480  and this [commit](https://github.com/open-mmlab/mmdetection/commit/727d867119f30434921ae581586c070dd737ad71) in mmdet, 1. '--amp' option 2. auto-scale lr 3. auto-resume
are supported in this pr.
> [Feature] Update train

- configs/nas/mmcls/darts/metafile.yml
- Fix config path error in metafile.yaml of Darts.
**Before PR**:
**After …
> [Fix] Fix darts metafile

- mmrazor/engine/runner/evolution_search_loop.py
- mmrazor/engine/runner/subnet_sampler_loop.py
- mmrazor/engine/runner/utils/__init__.py
- mmrazor/engine/runner/utils/check.py
- mmrazor/structures/subnet/candidate.py
- tests/test_models/test_subnet/test_candidate.py
- tests/test_runners/test_evolution_search_loop.py
- tests/test_runners/test_subnet_sampler_loop.py
- tests/test_runners/test_utils/test_check.py
Reverts open-mmlab/mmrazor#316
> Revert "[Improvement] Support for candidate multiple dimensional search constraints."

- .github/workflows/build.yml
- mmrazor/__init__.py
- mmrazor/core/searcher/evolution_search.py
- requirements/optional.txt
- tests/test_core/test_searcher.py
Fixed the pending bug when implementing DetNAS
**Before PR**:
**After PR**:
> [Fix] Fixed evolution search pending

- mmrazor/models/distillers/ofd_distiller.py
- mmrazor/models/task_modules/predictor/handler/carts_handler.py
- mmrazor/models/task_modules/predictor/handler/gp_handler.py
- mmrazor/models/task_modules/predictor/handler/mlp_handler.py
- mmrazor/models/task_modules/predictor/handler/rbf_handler.py
- mmrazor/models/task_modules/predictor/metric_predictor.py
- mmrazor/utils/placeholder.py
- requirements/optional.txt
- tests/test_models/test_mutables/test_mutable_channel/test_units/test_dcff_channel_unit.py
- tests/test_models/test_mutables/test_mutable_channel/test_units/test_mutable_channel_units.py
> [Fix] Fix optional requirements

- .dev_scripts/benchmark_test.py
- configs/distill/mmdet/pkd/pkd_fpn_retina_x101_retina_r50_2x_coco.py
- configs/nas/mmcls/autoslim/metafile.yml
- configs/nas/mmcls/darts/metafile.yml
fix bug in configs
fix bug in benchmark_test
> fix bug in benchmark_test

- .github/workflows/build.yml
update `test_linux:matrix` to torch1.13.
> [CI] Update ci to torch1.13

- mmrazor/utils/placeholder.py
- tests/test_utils/test_placeholder.py
> fix bug in placer holder

- mmrazor/models/algorithms/distill/configurable/single_teacher_distill.py
Set `requires_grad` of params to False if the teacher is not trainable, this would prevent from setting `find_unused_parameters` to True, which is dangerous for some cases.
Set the requires_grad of param to False is the teacher is not trainable
If this PR introduces a new …
> Set requires_grad to False if the teacher is not trainable

- mmrazor/models/__init__.py
- mmrazor/models/chex/__init__.py
- mmrazor/models/chex/chex_algorithm.py
- mmrazor/models/chex/chex_mutator.py
- mmrazor/models/chex/chex_ops.py
- mmrazor/models/chex/chex_unit.py
- mmrazor/models/chex/utils.py
- tests/test_chex/test_chex_algorithm.py
- tests/test_chex/test_chex_mutator.py
- tests/test_chex/test_chex_ops.py
add Chex ops, Chex mutator and algorithm
> add Chex ops, Chex mutator and algorithm

- mmrazor/models/observers/__init__.py
- mmrazor/models/observers/minmaxfloor_observer.py
- mmrazor/models/quantizers/trt_quantizer.py
- tests/test_models/test_observers/test_observer.py
MinMaxFloorObserver is implemented based on pytorch.
Add minmaxfloor_observer.py.
> CodeCamp #132 add MinMaxFloorObserver

- configs/chex/resnet50/resource.py
- mmrazor/models/chex/__init__.py
- mmrazor/models/chex/chex_mutator.py
- mmrazor/models/chex/chex_unit.py
- mmrazor/models/chex/counters.py
- tests/test_chex/test_chex_mutator.py
- tools/pruning/get_resource.py
> Chex update

- configs/chex/resnet50/chex_resnet50_imagenet.py
1. revise the loss of model to LabelSmoothLoss
> [CHEX] revise the loss of model to LabelSmoothLoss

- mmrazor/version.py
> Bump version to 1.0.0rc2

- docs/en/advanced_guides/customize_quantization_algorithms.md
- docs/en/advanced_guides/index.rst
> add customize_quantization_tutorial

- README.md
- docs/en/user_guides/index.rst
- docs/en/user_guides/quantization_user_guide.md
> [Docs] Add quantization user guide

- mmrazor/models/quantizers/native_quantizer.py
> [Bug] Fix del redundant fakequant

- .pre-commit-config.yaml
- mmrazor/apis/mmcls/train.py
> [Fix] Fix `split` in Darts config

- mmrazor/models/task_modules/tracer/channel_analyzer.py
make channel analyzer try different forward modes to adaptive more models.
> make channel analyzer try different forward mode.

- configs/quantization/deploy_cfgs/mmcls/classification_openvino_dynamic-224x224.py
- configs/quantization/deploy_cfgs/mmdet/detection_openvino_dynamic-800x1344.py
- configs/quantization/ptq/ptq_openvino_resnet18_8xb32_in1k_calib32xb32.py
- configs/quantization/ptq/ptq_openvino_retina_r50_1x_coco_calib32xb32.py
- mmrazor/models/algorithms/quantization/mm_architecture.py
- mmrazor/models/quantizers/openvino_quantizer.py
> [Feature]Rewrite the origin model during prepare

- tests/test_models/test_task_modules/test_custom_tracer.py
class ToyModel(torch.nn.Module):
def __init__(self):
super.__init__()
super().__init__()
def get_loss(self, x):
return x * 0.1
> test case super problem

- mmrazor/implementations/pruning/__init__.py
- mmrazor/implementations/pruning/sparse_gpt/__init__.py
- mmrazor/implementations/pruning/sparse_gpt/mutator.py
- mmrazor/implementations/pruning/sparse_gpt/ops.py
- mmrazor/implementations/pruning/sparse_gpt/sparse24_utils.py
- mmrazor/implementations/pruning/sparse_gpt/utils.py
- projects/sparse_gpt/llm/datautils.py
- projects/sparse_gpt/llm/opt_sparse.py
- projects/sparse_gpt/pipe.py
- projects/sparse_gpt/torch_sample.py
- tests/test_impl/test_pruning/test_sparse_gpt/test_op.py
add sparse gpt to prune linear and conv2d. here includes two examples of renset18 and opt language model.
> add sparse gpt

- .github/workflows/build.yml
> [Bug] Fix ci converage setting

- configs/pruning/mmpose/dcff/fix_subnet.json
> [Bug] fix a rebase error

- README.md
- README_zh-CN.md
> [Docs] Checkout readthedocs to latest

- docs/en/advanced_guides/customize_nas_algorithms.md
> [Docs] Fix the link in readthedocs
